### ISSUE TITLE
Overloading with optional parameters

### ISSUE THREAD

**Issue by fsantini-vs** [coady/multimethod#16]
Hi,

The following example produces an error:
`
class A:
    @multimethod
    def m(self, c: int, ii: Optional[int] = None):
        print('1', c, ii)

    @multimethod
    def m(self, ff: float):
        print('2', ff)

obj = A()
obj.m(20)
`

when calling `obj.m(20)`:
`
  File "/usr/local/lib/python3.8/dist-packages/multimethod/__init__.py", line 184, in __call__
    return self[tuple(map(self.get_type, args))](*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/multimethod/__init__.py", line 180, in __missing__
    raise DispatchError(msg, types, keys)
multimethod.DispatchError: ('a: 0 methods found', (<class '__main__.A'>, <class 'int'>), [])

Process finished with exit code 1
`

Is there a way around it?

**Comment by coady** [comment]
Support dispatching on defaults is difficult, but there is a workaround.  Use overloading itself to specify defaults:
```python
class A:
     @multimethod
     def m(self, c: int, ii: Optional[int]):
         print('1', c, ii)

     @multimethod
     def m(self, c: int):
         return self.m(c, None)
```

**Comment by hzhangxyz** [comment]
it seems not work for keyward argument?

**Comment by coady** [comment]
> it seems not work for keyward argument?

Keywords arguments are allowed but don't participate in the dispatch.  As with defaults, it would be inefficient to implement.  Instead of comparing tuples to types, the dispatch would have to compute the equivalent of [Signature.bind](https://docs.python.org/3/library/inspect.html#inspect.Signature.bind) for each call.  Which is what `overload` does.

**Comment by hzhangxyz** [comment]
Since you use `return self[tuple(map(self.get_type, args))](*args, **kwargs)` to detect which func to call, I think it is a good choice to ignore keyword only argment when define multimethod.

For example
```
@multimethod
def f(int a, int b, *, int c, int d):
    pass
```
will return multimethod `{(<class int>, <class int>): <function>}`, instead of `{(<class int>, <class int>, <class int>, <class int>): <function>}`

**Comment by coady** [comment]
Seems like I misunderstood this request. I still think it's infeasible to _dispatch_ on default and keywords arguments. But if the goal is simply to allow - and ignore - annotations on default and keyword parameters, that sounds reasonable.
